namespace A1.Models
{
    public static class DbInitializer
    {
        public static void Seed(IApplicationBuilder applicationBuilder)
        {
            A1DbContext context =
                applicationBuilder.ApplicationServices.CreateScope().ServiceProvider.GetRequiredService<A1DbContext>();

            if (!context.Treatments.Any())
            {
                context.AddRange
                (
                    new Treatment { TreatmentName = "Emergency Dentist", Price = 149.99M, Description = "Are you in pain? Do you need an emergency dentist?\r\nDental emergencies can include toothache, dental injuries like missing teeth, because they've been knocked our during sport. Other dental emergencies can include fractured teeth, facial swelling, or lost fillings.\r\n\r\nYou can call us or book an urgent appointment online. Our practice is open after hours during the week, or on Saturdays, for your convenience.", ImageThumbnailUrl = "Images/treatments/emergency.jpg", ImageUrl = "Images/treatments/emergency-1.jpg", IsOnPromotion = false},
                    new Treatment { TreatmentName = "Exam & X-Rays Check-Up", Price = 59.99M, Description = "A regular check-up with a dentist is your first step to better oral health.\r\nWhen you book with us for a routine exam and x-rays check-up your teeth and mouth will thank you. Well, they would if they could talk.\r\n\r\nHaving regular routine dental check-ups means you’re less likely to need to see an emergency dentist. And we know that over time, people who visit a dental clinic regularly spend less money.", ImageThumbnailUrl = "Images/treatments/x-rays.jpg", ImageUrl = "Images/treatments/x-rays-1.jpg", IsOnPromotion = false},
                    new Treatment { TreatmentName = "Hygiene Services", Price = 89.99M, Description = "You only have one smile, for life. Regular hygiene treatments will help keep your smile happy and healthy.\r\nThere are two simple steps to good oral hygiene - regular visits to your dentist and hygienist, and good oral health care at home.\r\n\r\nIt's so important to look after your oral hygiene to keep your teeth and gums healthy and limit the chance of dental problems in the future.", ImageThumbnailUrl = "Images/treatments/dental-hygiene.jpg", ImageUrl = "Images/treatments/dental-hygiene-1.jpg", IsOnPromotion = false},
                    new Treatment { TreatmentName = "Fillings", Price = 349.99M, Description = "Fillings are a common dental treatment that fix a hole in your tooth caused by decay.\r\nThink you might need a filling? Fillings are very common and most people will need one at some stage in their lives. It’s important to take good care of your oral health to reduce the chance of needing a filling.\r\n\r\nIf you need a filling your dentist will first remove the caries, or decay, from inside your tooth and then fill the cavity with one of a wide range of filling materials.", ImageThumbnailUrl = "Images/treatments/fillings.jpg", ImageUrl = "Images/treatments/fillings-1.jpg", IsOnPromotion = true},
                    new Treatment { TreatmentName = "Dentures", Price = 669.99M, Description = "Missing teeth? Dentures are custom-made to restore your smile.\r\nWe're New Zealand's dental industry leaders and our competitive dentures prices and flexible payment options could be the ideal option for you.\r\n\r\nDentures have been helping people for many years and they’ve come a long way since then. They’re no longer an old-fashioned, removable set of false teeth that sit in a glass of water next to your bed.", ImageThumbnailUrl = "Images/treatments/dentures.jpg", ImageUrl = "Images/treatments/dentures-1.jpg", IsOnPromotion = false},
                    new Treatment { TreatmentName = "Root Canals", Price = 439.99M, Description = "Feeling nervous about getting a root canal? No need to worry. Millions of teeth are saved each year with root canal treatment.\r\nRoot canals are life-changing. They help dentists and endodontists to save millions of teeth from being extracted, every year. The goal of a root canal, also known as endodontic treatment, is to save a tooth that has been badly damaged from decay, disease or injury.\r\n\r\nWith root canal treatment, patients are able to keep their own teeth rather than having them removed. Your own teeth are better than artificial teeth.", ImageThumbnailUrl = "Images/treatments/endodontiscs.jpg", ImageUrl = "Images/treatments/endodontiscs-1.jpg", IsOnPromotion = true},
                    new Treatment { TreatmentName = "Tooth Extraction", Price = 229.99M, Description = "If you need a tooth extracted you may feel nervous. There’s no need to worry.\r\nTooth extraction is the removal of a tooth from your jaw bone. Tooth extraction usually occurs when there’s too much damage to a tooth and can't be repaired. Decay, infection and crowding are also reasons that a dentist will extract a tooth.\r\n\r\nTooth extraction is often performed by a dentist but in some cases you will need to see an oral surgeon to have a tooth or teeth extracted. Don’t stress. It's usually a quick procedure that's not as bad as you have imagined.", ImageThumbnailUrl = "Images/treatments/extractions.jpg", ImageUrl = "Images/treatments/extractions-1.jpg", IsOnPromotion = false},
                    new Treatment { TreatmentName = "Wisdom Teeth Removal", Price = 249.99M, Description = "Getting your wisdom teeth removed is a fairly common procedure. You might feel nervous about it, but you can relax. It’s not as bad as you might think.\r\nIf you’ve been told you need your wisdom teeth removed, you could feel a little concerned. There’s no need to be anxious. Our team of gentle dentists make getting your wisdom teeth removed as easy and stress-free as possible. And having your wisdom teeth removed will put an end to the pain and discomfort that you may have been experiencing.", ImageThumbnailUrl = "Images/treatments/wisdom-teeth.jpg", ImageUrl = "Images/treatments/wisdom-teeth-1.jpg", IsOnPromotion = false},
                    new Treatment { TreatmentName = "Custom-Made Mouthguards", Price = 299.99M, Description = "There’s always risks with any sport. With custom-made mouthguards, losing your teeth doesn’t have to be one of them.\r\nAccidents happen – especially during contact sports games. Custom-made mouthguards are the most effective way you can protect your mouth and teeth while playing sports. They reduce your chance of sustaining an oral injury by around 90% and help prevent painful accidents or damage.", ImageThumbnailUrl = "Images/treatments/mouthguards.jpg", ImageUrl = "Images/treatments/mouthguards-1.jpg", IsOnPromotion = true},
                    new Treatment { TreatmentName = "Sedation", Price = 44.99M, Description = "If you're a nervous patient, sedation might be a good option for you. It can help you feel more relaxed during your dental treatment.\r\nIt’s common to feel a little anxious about visiting the dentist. Fortunately, there are different ways that our dentists can make you feel more comfortable during treatment. One of the most useful ways to relax you during dental treatments is with sedation. Patients often choose sedation for very complex dental treatments or surgery, including wisdom tooth removal or dental implants.", ImageThumbnailUrl = "Images/treatments/sedation.jpg", ImageUrl = "Images/treatments/sedation-1.jpg", IsOnPromotion = false},
                    new Treatment { TreatmentName = "Sleep Apnoea Appliances", Price = 99.99M, Description = "Do you wake up tired every day? Do other people tell you that you snore while you sleep?\r\nIf your answer is yes, you might benefit from using a custom-made sleep apnoea dental appliance. Sleep apnoea can have a huge impact on your life. If it's left untreated it can lead to more serious health issues. Sleep apnoea is a common condition that causes you to stop breathing during your sleep. Typically, symptoms include snoring, not feel refreshed when you wake up and daytime sleepiness. Even though you stop breathing, briefly and often, you’re not usually aware of it.", ImageThumbnailUrl = "Images/treatments/sleep-apnoea.jpg", ImageUrl = "Images/treatments/sleep-apnoea-1.jpg", IsOnPromotion = false},
                    new Treatment { TreatmentName = "TMJ", Price = 119.99M, Description = "Temporomandibular joint dysfunction, commonly known as TMJ syndrome, can be incredibly painful.\r\nIf you’ve ever experienced jaw pain you’ll know how frustrating it is. It can have a big impact on your life. TMJ is one of the common causes of jaw pain. It can cause a lot of unnecessary stress, because it affects you every time you eat and talk. \r\n\r\nMany people with TMJ experience constant jaw pain, have difficulty chewing and locking their jaw joint. If left untreated it can get worse and cause even more problems for you. It can become more difficult to treat and can often cause chronic headaches.", ImageThumbnailUrl = "Images/treatments/tmj.jpg", ImageUrl = "Images/treatments/tmj-1.jpg", IsOnPromotion = false}
                );
            }

            if (!context.Staffs.Any())
            {
                context.AddRange
                (
                    new Staff { StaffId = "D001", FirstName = "John", LastName = "Doe", Password = "password", Position = "Dentist", WorkEmail = "JD123@gmail.com", WorkPhone = "027 362 7800" },
                    new Staff { StaffId = "D002", FirstName = "Jane", LastName = "Noe", Password = "password", Position = "Dental Hygienist", WorkEmail = "JN456@gmail.com", WorkPhone = "026 352 7801" },
                    new Staff { StaffId = "D003", FirstName = "Jack", LastName = "Troll", Password = "password", Position = "Dental Assistant", WorkEmail = "JT789@gmail.com", WorkPhone = "021 222 8888" }
                );
            }

            context.SaveChanges();
        }
    }
}
